version: "3.7"
services:
  ui:
    image: slangenmaier/airrow-ui:donumenta-latest
    ports:
      - "${UI_PORT}:80"
  api:
    image: slangenmaier/airrow:donumenta-latest
    volumes:
      - appdata:/data
    ports:
      - "${API_PORT}:8080"
    environment:
      - SEARCH_WALK_DISTANCE=1500m
      - SEARCH_SCALE=0.9
      - SEARCH_MIN_ACCURACY=25
      - STORAGE_DIRECTORY=/data/
      - ADMIN_CREATOR=""
      - QUARKUS_ELASTICSEARCH_HOSTS=es:9200
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      - "${ES_PORT}:9200"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms196m -Xmx196m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
volumes:
  esdata:
  appdata:
